site_name: My Python Cheat Sheet
# pip install mkdocstrings[python]>=0.18 per installare Griffe altrimenti nun va
nav:
  - Sheet 1: 'sheet_1.md'


plugins:
  - search
  - mkdocstrings:
      docstring_style: google  # or "numpydoc"
      processes:
        private-members: true
  


theme:
  name: material

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode